### PR TITLE
Support Mac m1 arm builds

### LINKED ISSUE #25: Mac M1 support
hi

Would like to start using this provider, I have recently started using a new Mac with the arm M1 chip and would need a Darwin_arm64 build. Go 1.16 supports this and the new releases of goreleaser supports generating that build (https://github.com/goreleaser/goreleaser/releases/tag/v0.156.2). I'm happy to try and create a PR, looks like the main changes would be in GitHub Actions and dockerfile.test, assuming not much change to actual code.

thanks
Andrew

### PR DESCRIPTION
**Pull request by acraftydev**
fixes kristofferahl/terraform-provider-healthchecksio#25

bumps version for go and goreleases

### CODE REVIEW

**Comment by kristofferahl** [comment]
At first glance it looks good. Will take a closer look as soon as possible. One thing though, did we not have to add something to goreleaser file for M1?

**Comment by acraftydev** [comment]
> At first glance it looks good. Will take a closer look as soon as possible. One thing though, did we not have to add something to goreleaser file for M1?

It is included but ignored in older versions of goreleaser, so bumping version has started building it. From goreleaser release notes for version v1.156.2, https://github.com/goreleaser/goreleaser/releases/tag/v0.156.2 : 

> GOOS=darwin GOARCH=arm64 was ignored before this release, since it was a build for iOS that most people didn't care about and required more than just go to build.

**Comment by kristofferahl** [comment]
Perfect! Will try and check it out tomorrow. 👌

**Review by kristofferahl — APPROVED** [review]
LGTM! Will merge and do some further testing before creating a new release. Will let you know.

**Comment by kristofferahl** [comment]
@acraftydev A new release (v1.9.0) is now ready and available in the terraform registry and on github.

- https://registry.terraform.io/providers/kristofferahl/healthchecksio/latest
- https://github.com/kristofferahl/terraform-provider-healthchecksio/releases/tag/v1.9.0

Please give it a spin and let me know if everything is working as expected.
Thanks again for helping out! 🥇 👍

**Comment by acraftydev** [comment]
all working as expected thanks

**Pull request merged**
