### PR TITLE
Feature: Go modules

### PR DESCRIPTION
**Pull request by kristofferahl**
No real experience with go modules before but these are the files I got after running the following:
- go mod init
- go mod tidy

Would be great if someone could very it work and let me know if anything else is needed?

### CODE REVIEW

**Comment by masutaka** [comment]
✅ It seems no problem to build the binary.

```
$ export GO111MODULE=on
$ go mod download
$ ./run build
```

:bulb: It might be useful to add `export GO111MODULE=on` to `run` script until go-1.13 releases.

By the way, it seems that contents in the `dist` directory are strange. Is `{{ .ProjectName }}_{{ .Tag }}` correct?

```
$ ls dist
checksums.txt                                                           terraform-provider-healthchecksio_v1.3.0-next_Linux_x86_64.tar.gz
config.yaml                                                             {{ .ProjectName }}_{{ .Tag }}_darwin_386
terraform-provider-healthchecksio_v1.3.0-next_Darwin_i386.tar.gz        {{ .ProjectName }}_{{ .Tag }}_darwin_amd64
terraform-provider-healthchecksio_v1.3.0-next_Darwin_x86_64.tar.gz      {{ .ProjectName }}_{{ .Tag }}_linux_386
terraform-provider-healthchecksio_v1.3.0-next_Linux_i386.tar.gz         {{ .ProjectName }}_{{ .Tag }}_linux_amd64
```

✅ The unit test is passed.

```
$ ./run test
2019-06-20 00:27:28 [INF] [run] Running unit tests...
ok      command-line-arguments  (cached)
```

:warning: The integration test fails. Do you get the following failure?

```
$ ./run test-integration
2019-06-20 00:31:01 [INF] [run] Running integration tests (Terraform v0.12.2)...
2019-06-20 00:31:01 [INF] [run] Test: minimal (/Users/masutaka/src/github.com/kristofferahl/terraform-provider-healthchecksio/test/minimal)
2019-06-20 00:31:01 [INF] [run] Installing plugin (src=/Users/masutaka/src/github.com/kristofferahl/terraform-provider-healthchecksio/dist dest=/Users/masutaka/src/github.com/kristofferahl/terraform-provider-healthchecksio/test/minimal)

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

Provider "healthchecksio" not available for installation.

A provider named "healthchecksio" could not be found in the Terraform Registry.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/darwin_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".


Error: no provider exists with the given name
```

**Comment by kristofferahl** [comment]
@masutaka Thanks for the review. I'll give an update here soon!

**Comment by kristofferahl** [comment]
@masutaka Haven't really had the time to complete this PR, so don't merge it yet. But..

I had a look at your comments and found the issue with weird names in dist file names. It seems goreleaser have remove support for templated binary names. At least I can't find how to make it work in later version. Will look at it again before merging the PR.

Also the failing integration tests is likely because of changes in goreleaser. So, downgrading to **goreleaser 0.85.1** fixes things for now.

Also made it possible to run most commands in the `run` script in docker.
```bash
./run <command>
./run docker <command>
```
Some commands are really slow running in docker but I'll try and fix that too.

To be continued...

**Comment by kristofferahl** [comment]
@masutaka Managed to get things working with v0.110.0 of goreleaser. There is a bug (https://github.com/goreleaser/goreleaser/issues/1059) that needed some hacks on our part but It's not that bad. Using the ./run docker <command> is still slow for the most part but I think that's OK for now. It should work and that's the most important thing.

If you have the time to try out this PR again it would be great. Just want to make sure things work (although slow) before we merge the PR.

Let me know if anything else needs fixing!

**Comment by masutaka** [comment]
Thanks! I'll review this weekend.

**Review by masutaka — APPROVED** [review]
* :white_check_mark: `$ ./run build`
* :white_check_mark: `$ ls dist`

    ```
    checksums.txt        dist_linux_amd64
    config.yaml          terraform-provider-healthchecksio_v1.3.0-next_Darwin_i386.tar.gz
    dist_darwin_386      terraform-provider-healthchecksio_v1.3.0-next_Darwin_x86_64.tar.gz
    dist_darwin_amd64    terraform-provider-healthchecksio_v1.3.0-next_Linux_i386.tar.gz
    dist_linux_386       terraform-provider-healthchecksio_v1.3.0-next_Linux_x86_64.tar.gz
    ```

* :white_check_mark: `$ ./run test`
* :white_check_mark: `$ ./run test-integration`
* :white_check_mark: `$ ./run docker test`
* :white_check_mark: `$ ./run docker test-integration`

**Comment by kristofferahl** [comment]
Thanks @masutaka !

**Pull request merged**
