### PR TITLE
terraform 0.12 fix for channels list, documentation enhancements

### PR DESCRIPTION
**Pull request by rossmckelvie**
The provider almost works out of the box with terraform 0.12 when compiled with the latest version of the schema SDKs. I updated `channels` property to be a list of strings.

I also added documentation for additional data provider kinds (pagerduty is abbreviated pd, hopefully this helps save somebody time in the future), added a method I'm using to keep secrets out of the codebase, and split the examples into 2 files (full.tf and minimal.tf).

### CODE REVIEW

**Comment by kristofferahl** [comment]
Big thanks @rossmckelvie ! I'll have a look at it.

**Comment by kristofferahl** [comment]
@rossmckelvie Help me understand the changes proposed. From what I've read, Terraform 0.12 introduces some new syntax and other features.

- Are all the changes made required to make the provider work with T 0.12?
- Is it backwards compatible in terms of syntax?
```channels = [data.healthchecksio_channel.pagerduty.id]```
vs.
```channels = ["${data.healthchecksio_channel.pagerduty.id}"]```
If so, I think we should downgrade the examples syntax to be compatible with both 0.11 and 0.12.

Let me know what do you think and I'll get merging?

**Comment by rossmckelvie** [comment]
The provider as-is does not work with 0.12. At a minimum, it needs to be recompiled with the latest terraform sdk, and then you can join the list of channels together as a string in 0.12 or use the newer syntax like I did for the examples.

I have many crons and would prefer being able to use the enhancements of 0.12. If you install terraform fresh today, ala `brew install terraform` you’re going to get 0.12 and the example syntax doesn’t work in its 0.11 form, I can get an exact error message when I get to work.

**Comment by masutaka** [comment]
Should we introduce Go Modules?

**Comment by kristofferahl** [comment]
@rossmckelvie Seems to be working as expected. I'll merge it as is! Will let you know when a new release is ready (shouldn't be long).

@masutaka Introducing go modules sounds like a good idea. I'll have a "go" at it once the PR is merged.

**Review by kristofferahl — APPROVED** [review]

**Comment by kristofferahl** [comment]
@rossmckelvie Decided to create a new release (v1.3.0) containing this PR. Thanks for the help!

**Pull request merged**
