### PR TITLE
Support channels

### PR DESCRIPTION
**Pull request by masutaka**
:warning: This PR is blocked by https://github.com/kristofferahl/go-healthchecksio/pull/1

At last we can manage Healthcheck `channels`!

You may know how to use by `examples/test.tf`. See also https://healthchecks.io/docs/api/

### CODE REVIEW

**Review by kristofferahl — APPROVED** [review]
Looks good to me. Go ahead and merge it once the block has been resolved.
 
Thanks! 🥇

**Comment by kristofferahl** [comment]
@masutaka Let me know when the PR is merged and I can release new binaries!

**Comment by masutaka** [comment]
You are welcome! I'm looking forward to the new release. :smile:

**Comment by kristofferahl** [comment]
@masutaka New release (v.1.2.0) is now available on github. Sorry for the delay!

**Comment by masutaka** [comment]
Thanks!!!! :smile:

**Pull request merged**
